export const REPORT_PURCHASES = 'reportPurchases'

// Getters
export const REPORT_INPUT_RECEIPT_DETAILS_GETTER = 'REPORT_INPUT_RECEIPT_DETAILS_GETTER'
export const PRINT_REPORT_INPUT_RECEIPT_DETAILS_GETTER = 'PRINT_REPORT_INPUT_RECEIPT_DETAILS_GETTER'
// Actions
export const GET_REPORT_INPUT_RECEIPT_DETAILS_ACTION = 'GET_REPORT_INPUT_RECEIPT_DETAILS_ACTION'
export const EXPORT_REPORT_INPUT_RECEIPT_DETAILS_ACTION = 'EXPORT_REPORT_INPUT_RECEIPT_DETAILS_ACTION'
export const PRINT_REPORT_INPUT_RECEIPT_DETAILS_ACTION = 'PRINT_REPORT_INPUT_RECEIPT_DETAILS_ACTION'
