export const REPORT_WAREHOUSES_DIFFERENCE_PRICE = 'reportWarehousesDifferencePrice'

// Getters
export const GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_GETTER = 'GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_GETTER'
export const PRODUCT_CAT_GETTER = 'PRODUCT_CAT_GETTER'
export const PRODUCT_GETTER = 'PRODUCT_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION = 'GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION'
export const GET_PRODUCT_ACTION = 'GET_PRODUCT_ACTION'
export const GET_PRODUCT_CAT_ACTION = 'GET_PRODUCT_CAT_ACTION'
export const EXPORT_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION = 'EXPORT_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION'
