export const REPORT_WAREHOUSES_DIFFERENCE_PRICE = 'reportWarehousesDifferencePrice'

// Getters
export const GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_GETTER = 'GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_GETTER'
export const PRODUCT_CAT_LISTS_GETTER = 'PRODUCT_CAT_LISTS_GETTER'
export const PRODUCT_LISTS_GETTER = 'PRODUCT_LISTS_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION = 'GET_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION'
export const GET_PRODUCT_LISTS_ACTION = 'GET_PRODUCT_LISTS_ACTION'
export const GET_PRODUCT_CAT_LISTS_ACTION = 'GET_PRODUCT_CAT_LISTS_ACTION'
export const EXPORT_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION = 'EXPORT_REPORT_WAREHOUSES_DIFFERENCE_PRICE_ACTION'
