export const REDINVOICE = 'salesRedBills'

// Getters
export const REDINVOICES_GETTER = 'REDINVOICES_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const GET_BILL_OF_SALES_GETTER = 'GET_BILL_OF_SALES_GETTER'
export const GET_BILL_OF_SALES_SELECTED_PRODUCTS_GETTER = 'GET_BILL_OF_SALES_SELECTED_PRODUCTS_GETTER'

// Mutations
export const CLEAR_BILL_OF_SALE_PRODUCTS_UNCHECKED = 'CLEAR_BILL_OF_SALE_PRODUCTS_UNCHECKED'
export const CLEAR_ALL_BILL_OF_SALES_PRODUCTS = 'CLEAR_ALL_BILL_OF_SALES_PRODUCTS'

// Actions
export const GET_REDINVOICES_ACTION = 'GET_REDINVOICES_ACTION'
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const GET_BILL_OF_SALES_ACTION = 'GET_BILL_OF_SALES_ACTION'
export const GET_BILL_OF_SALE_SELECTED_PRODUCT_ACTION = 'GET_BILL_OF_SALES_SELECTED_PRODUCT_ACTION'
