export const REDINVOICE = 'salesRedBills'

// Getters
export const REDINVOICES_GETTER = 'REDINVOICES_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'

// Actions
export const GET_REDINVOICES_ACTION = 'GET_REDINVOICES_ACTION'
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
