export const RED_INVOICE = 'salesRedBills'

// Getters
export const RED_INVOICES_GETTER = 'RED_INVOICES_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const GET_BILL_OF_SALES_GETTER = 'GET_BILL_OF_SALES_GETTER'
export const GET_PRODUCTS_IN_SELECTED_BILL_GETTER = 'GET_PRODUCTS_IN_SELECTED_BILL_GETTER'
export const PRODUCTS_GETTER = 'PRODUCTS_GETTER'
export const GET_INVOICE_DETAIL_GETTER = 'GET_INVOICE_DETAIL_GETTER'
export const GET_INVOICE_DETAIL_INFO_GETTER = 'GET_INVOICE_DETAIL_INFO_GETTER'

// Mutations
export const CLEAR_BILL_OF_SALE_PRODUCTS_UNCHECKED = 'CLEAR_BILL_OF_SALE_PRODUCTS_UNCHECKED'
export const CLEAR_ALL_BILL_OF_SALES_PRODUCTS = 'CLEAR_ALL_BILL_OF_SALES_PRODUCTS'

// Actions
export const GET_RED_INVOICES_ACTION = 'GET_RED_INVOICES_ACTION'
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const GET_BILL_OF_SALES_ACTION = 'GET_BILL_OF_SALES_ACTION'
export const GET_PRODUCTS_IN_SELECTED_BILL_ACTION = 'GET_PRODUCTS_IN_SELECTED_BILL_ACTION'
export const GET_PRODUCTS_ACTION = 'GET_PRODUCTS_ACTION'
export const CREATE_RED_BILL_ACTION = 'CREATE_RED_BILL_ACTION'
export const GET_INVOICE_DETAIL_ACTION = 'GET_INVOICE_DETAIL_ACTION'
export const DELETE_RED_INVOICE_ACTION = 'DELETE_RED_INVOICE_ACTION'
export const EXPORT_RED_BILLS_ACTION = 'EXPORT_RED_BILLS_ACTION'
export const UPDATE_RED_BILLS_ACTION = 'UPDATE_RED_BILLS_ACTION'
