export const REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY = 'reportWarehousesInputOutputInventory'

// Getters
export const REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_GETTER = 'REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_GETTER'
export const PRODUCT_CAT_LISTS_GETTER = 'PRODUCT_CAT_LISTS_GETTER'
export const PRODUCT_LISTS_GETTER = 'PRODUCT_LISTS_GETTER'
// Mutations
export const CLEAR_ALL_PRODUCT_LISTS_CHECKED = 'CLEAR_ALL_PRODUCT_LISTS_CHECKED'
// Actions
export const GET_REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_ACTION = 'GET_REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_ACTION'
export const EXPORT_REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_ACTION = 'EXPORT_REPORT_WAREHOUSES_INPUT_OUTPUT_INVENTORY_ACTION'
export const GET_PRODUCT_LISTS_ACTIONS = 'GET_PRODUCT_LISTS_ACTIONS'
export const GET_PRODUCT_CAT_LISTS_ACTIONS = 'GET_PRODUCT_CAT_LISTS_ACTIONS'
