export const WAREHOUSES_EXCHANGE_DAMAGED_GOODS = 'warehousesExchangeDamagedGoods'

// Getters
export const EXCHANGE_DAMAGED_GOODS_GETTER = 'EXCHANGE_DAMAGED_GOODS_GETTER'
export const EXCHANGE_DAMAGED_GOODS_REASONS_GETTER = 'EXCHANGE_DAMAGED_GOODS_REASONS_GETTER'
export const EXCHANGE_DAMAGED_GOODS_BY_ID_GETTER = 'EXCHANGE_DAMAGED_GOODS_BY_ID_GETTER'
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const PRODUCTS_GETTER = 'PRODUCTS_GETTER'
export const DAMAGED_GOODS_GETTER = 'DAMAGED_GOODS_GETTER'

// Actions
export const GET_EXCHANGE_DAMAGED_GOODS_ACTION = 'GET_EXCHANGE_DAMAGED_GOODS_ACTION'
export const GET_EXCHANGE_DAMAGED_GOODS_REASONS_ACTION = 'GET_EXCHANGE_DAMAGED_GOODS_REASONS_ACTION'
export const CREATE_EXCHANGE_DAMAGED_GOODS_ACTION = 'CREATE_EXCHANGE_DAMAGED_GOODS_ACTION'
export const GET_EXCHANGE_DAMAGED_GOODS_BY_ID_ACTION = 'GET_EXCHANGE_DAMAGED_GOODS_BY_ID_ACTION'
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const GET_PRODUCTS_ACTION = 'GET_PRODUCTS_ACTION'
export const UPDATE_EXCHANGE_DAMAGED_GOODS_ACTION = 'UPDATE_EXCHANGE_DAMAGED_GOODS_ACTION'
export const GET_DAMAGED_GOODS_ACTION = 'GET_DAMAGED_GOODS_ACTION'
