export const WAREHOUSESEXCHANGEDAMAGEDGOODS = 'warehousesExchangeDamagedGoods'

// Getters

export const EXCHANGE_DAMAGED_GOODS_GETTER = 'EXCHANGE_DAMAGED_GOODS_GETTER'
export const EXCHANGE_DAMAGED_GOODS_PAGINATION_GETTER = 'EXCHANGE_DAMAGED_GOODS_PAGINATION_GETTER'

// Actions
export const GET_EXCHANGE_DAMAGED_GOODS_ACTION = 'GET_EXCHANGE_DAMAGED_GOODS_ACTION'
