export const EXPORT = 'warehousesOutput'

// Getters
export const GET_EXPORTS_GETTER = 'GET_EXPORTS_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const GET_EXPORT_BY_ID_GETTER = 'GET_EXPORT_BY_ID_GETTER'
export const GET_PRODUCTS_OF_EXPORT_GETTER = 'GET_PRODUCTS_OF_EXPORT_GETTER'

// Actions
export const GET_EXPORTS_ACTION = 'GET_EXPORTS_ACTION'
export const PRINT_EXPORT_ACTION = 'PRINT_EXPORT_ACTION'
export const GET_EXPORT_BY_ID_ACTION = 'GET_EXPORT_BY_ID_ACTION'
export const GET_PRODUCTS_OF_EXPORT_ACTION = 'GET_PRODUCTS_OF_EXPORT_ACTION'
export const UPDATE_EXPORT_ACTION = 'UPDATE_EXPORT_ACTION'
