export const WAREHOUSES_OUTPUT = 'warehousesOutput'

// Getters
export const GET_WAREHOUSES_OUTPUT_LIST_GETTER = 'GET_WAREHOUSES_OUTPUT_LIST_GETTER'
export const GET_WAREHOUSES_OUTPUT_BY_ID_GETTER = 'GET_WAREHOUSES_OUTPUT_BY_ID_GETTER'
export const GET_PRODUCTS_OF_WAREHOUSES_OUTPUT_GETTER = 'GET_PRODUCTS_OF_WAREHOUSES_OUTPUT_GETTER'

// Actions
export const GET_WAREHOUSES_OUTPUT_LIST_ACTION = 'GET_WAREHOUSES_OUTPUT_LIST_ACTION'
export const PRINT_WAREHOUSES_OUTPUT_ACTION = 'PRINT_WAREHOUSESOUTPUT_ACTION'
export const GET_WAREHOUSES_OUTPUT_BY_ID_ACTION = 'GET_WAREHOUSES_OUTPUT_BY_ID_ACTION'
export const GET_PRODUCTS_OF_WAREHOUSES_OUTPUT_ACTION = 'GET_PRODUCTS_OF_WAREHOUSES_OUTPUT_ACTION'
export const UPDATE_WAREHOUSES_OUTPUT_ACTION = 'UPDATE_WAREHOUSES_OUTPUT_ACTION'
