export const CUSTOMER = 'salesCustomers'

// Getters
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const SHOP_LOCATIONS_GETTER = 'SHOP_LOCATIONS_GETTER'

// Actions
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const CREATE_CUSTOMER_ACTION = 'CREATE_CUSTOMER_ACTION'
export const DELETE_CUSTOMERS_ACTION = 'DELETE_CUSTOMERS_ACTION'
export const GET_SHOP_LOCATIONS_ACTION = 'GET_SHOP_LOCATIONS_ACTION'
