export const CUSTOMER = 'salesCustomers'

// Getters
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const CUSTOMER_BY_ID_GETTER = 'CUSTOMER_BY_ID_GETTER'
export const CUSTOMER_TYPES_GETTER = 'CUSTOMER_TYPES_GETTER'
export const CUSTOMER_DEFAULT_GETTER = 'CUSTOMER_DEFAULT_GETTER'

export const SHOP_LOCATIONS_GETTER = 'SHOP_LOCATIONS_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const PROVINCES_GETTER = 'PROVINCES_GETTER'
export const DISTRICTS_GETTER = 'DISTRICTS_GETTER'
export const PRECINCTS_GETTER = 'PRECINCTS_GETTER'

export const CARD_TYPES_GETTER = 'CARD_TYPES_GETTER'
export const CLOSELY_TYPES_GETTER = 'CLOSELY_TYPES_GETTER'

export const SALEMT_PROMOTION_OBJECT_GETTER = 'SALEMT_PROMOTION_OBJECT_GETTER'
export const SALEMT_DELIVERY_TYPE_GETTER = 'SALEMT_SALEMT_DELIVERY_TYPE_GETTER'

// Actions
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const GET_CUSTOMER_BY_ID_ACTION = 'GET_CUSTOMER_BY_ID_ACTION'
export const CREATE_CUSTOMER_ACTION = 'CREATE_CUSTOMER_ACTION'
export const UPDATE_CUSTOMER_ACTION = 'UPDATE_CUSTOMER_ACTION'
export const GET_CUSTOMER_TYPES_ACTION = 'GET_CUSTOMER_TYPES_ACTION'
export const EXPORT_CUSTOMERS_ACTION = 'EXPORT_CUSTOMERS_ACTION'
export const GET_CUSTOMER_DEFAULT_ACTION = 'GET_CUSTOMER_DEFAULT_ACTION'

export const GET_SHOP_LOCATIONS_ACTION = 'GET_SHOP_LOCATIONS_ACTION'
export const GET_PROVINCES_ACTION = 'GET_PROVINCES_ACTION'
export const GET_DISTRICTS_ACTION = 'GET_DISTRICTS_ACTION'
export const GET_PRECINCTS_ACTION = 'GET_PRECINCTS_ACTION'

export const GET_CARD_TYPES_ACTION = 'GET_CARD_TYPES_ACTION'
export const GET_CLOSELY_TYPES_ACTION = 'GET_CLOSELY_TYPES_ACTION'

export const GET_SALEMT_PROMOTION_OBJECT_ACTION = 'GET_SALEMT_PROMOTION_OBJECT_ACTION'
export const GET_SALEMT_DELIVERY_TYPE_ACTION = 'GET_SALEMT_DELIVERY_TYPE_ACTION'
