export const CUSTOMER = 'salesCustomers'

// Getters
export const CUSTOMERS_GETTER = 'CUSTOMERS_GETTER'
export const CUSTOMER_TYPES_GETTER = 'CUSTOMER_TYPES_GETTER'
export const SHOP_LOCATIONS_GETTER = 'SHOP_LOCATIONS_GETTER'
export const ERROR_CODE_GETTER = 'ERROR_CODE_GETTER'
export const PROVINCES_GETTER = 'PROVINCES_GETTER'
export const DISTRICTS_GETTER = 'DISTRICTS_GETTER'
export const PRECINCTS_GETTER = 'PRECINCTS_GETTER'

// Actions
export const GET_CUSTOMERS_ACTION = 'GET_CUSTOMERS_ACTION'
export const CREATE_CUSTOMER_ACTION = 'CREATE_CUSTOMER_ACTION'
export const DELETE_CUSTOMERS_ACTION = 'DELETE_CUSTOMERS_ACTION'
export const GET_SHOP_LOCATIONS_ACTION = 'GET_SHOP_LOCATIONS_ACTION'
export const GET_CUSTOMER_TYPES_ACTION = 'GET_CUSTOMER_TYPES_ACTION'
export const GET_PROVINCES_ACTION = 'GET_PROVINCES_ACTION'
export const GET_DISTRICTS_ACTION = 'GET_DISTRICTS_ACTION'
export const GET_PRECINCTS_ACTION = 'GET_PRECINCTS_ACTION'
