export const REPORT_CUSTOMERS = 'reportsCustomers'

// Getters
export const REPORT_CUSTOMERS_GETTER = 'REPORT_CUSTOMERS_GETTER'
export const CUSTOMER_TYPES_GETTER = 'CUSTOMER_TYPES_GETTER'
export const SHOP_LOCATIONS_SEARCH_GETTER = 'SHOP_LOCATIONS_SEARCH_GETTER'

// Actions
export const GET_REPORT_CUSTOMERS_ACTION = 'GET_REPORT_CUSTOMERS_ACTION'
export const EXPORT_REPORT_CUSTOMERS_ACTION = 'EXPORT_REPORT_CUSTOMERS_ACTION'
export const GET_CUSTOMER_TYPES_ACTION = 'GET_CUSTOMER_TYPES_ACTION'
export const GET_SHOP_LOCATIONS_SEARCH_ACTION = 'GET_SHOP_LOCATIONS_SEARCH_ACTION'
