export const WAREHOUSEINPUT = 'warehousesInput'

// Getters
export const POCONFIRM_GETTER = 'POCONFIRM_GETTER'
export const PODETAIL_PRODUCTS_RES_GETTER = 'PODETAIL_PRODUCTS_RES_GETTER'
export const PODETAIL_PRODUCTS_PROMO_RES_GETTER = 'PODETAIL_PRODUCTS_PROMO_RES_GETTER'
export const PODETAIL_PRODUCTS_INFO_GETTER = 'PODETAIL_PRODUCTS_INFO_GETTER'
export const PODETAIL_PRODUCTS_PROMO_INFO_GETTER = 'PODETAIL_PRODUCTS_PROMO_INFO_GETTER'

export const IMPORT_ADJUSTMENTS_GETTER = 'IMPORT_ADJUSTMENTS_GETTER'
export const IMPORT_ADJUSTMENTS_DETAIL_GETTER = 'IMPORT_ADJUSTMENTS_DETAIL_GETTER'
export const IMPORT_BORROWINGS_GETTER = 'IMPORT_BORROWINGS_GETTER'
export const IMPORT_BORROWINGS_DETAIL_GETTER = 'IMPORT_BORROWINGS_DETAIL_GETTER'
export const RECEIPTS_GETTER = 'RECEIPTS_GETTER'

// Actions
export const GET_POCONFIRMS_ACTION = 'GET_POCONFIRMS_ACTION'
export const GET_PODETAIL_PRODUCTS_ACTION = 'GET_PODETAIL_PRODUCTS_ACTION'
export const GET_PODETAIL_PRODUCTS_PROMO_ACTION = 'GET_PODETAIL_PRODUCTS_PROMO_ACTION'
export const GET_IMPORTEXCEL_ACTION = 'GET_IMPORTEXCEL_ACTION'
export const GET_IMPORT_ADJUSTMENTS_ACTION = 'GET_IMPORT_ADJUSTMENTS_ACTION'
export const GET_IMPORT_ADJUSTMENTS_DETAIL_ACTION = 'GET_IMPORT_ADJUSTMENTS_DETAIL_ACTION'
export const GET_IMPORT_BORROWINGS_ACTION = 'GET_IMPORT_BORROWINGS_ACTION'
export const GET_IMPORT_BORROWINGS_DETAIL_ACTION = 'GET_IMPORT_BORROWINGS_DETAIL_ACTION'
export const UPDATE_NOT_IMPORT_ACTION = 'UPDATE_NOT_IMPORT_ACTION'
export const CREATE_SALE_IMPORT_ACTION = 'CREATE_SALE_IMPORT_ACTION'
export const GET_RECEIPTS_ACTION = 'GET_RECEIPTS_ACTION'
export const EXPORT_RECEIPTS_ACTION = 'EXPORT_RECEIPTS_ACTION'
