export const WAREHOUSEINPUT = 'warehousesInput'

// Getters
export const POCONFIRM_GETTER = 'POCONFIRM_GETTER'
export const PODETAIL_0_GETTER = 'PODETAIL_0_GETTER'
export const PODETAIL_1_GETTER = 'PODETAIL_1_GETTER'

export const IMPORT_ADJUSTMENTS_GETTER = 'IMPORT_ADJUSTMENTS_GETTER'
export const IMPORT_ADJUSTMENTS_DETAIL_GETTER = 'IMPORT_ADJUSTMENTS_DETAIL_GETTER'
export const IMPORT_BORROWINGS_GETTER = 'IMPORT_BORROWINGS_GETTER'
export const IMPORT_BORROWINGS_DETAIL_GETTER = 'IMPORT_BORROWINGS_DETAIL_GETTER'
export const RECEIPTS_GETTER = 'RECEIPTS_GETTER'

// Actions
export const GET_POCONFIRMS_ACTION = 'GET_POCONFIRMS_ACTION'
export const GET_PODETAIL_0_ACTION = 'GET_PODETAIL_0_ACTION'
export const GET_PODETAIL_1_ACTION = 'GET_PODETAIL_1_ACTION'
export const GET_IMPORTEXCEL_ACTION = 'GET_IMPORTEXCEL_ACTION'
export const GET_IMPORT_ADJUSTMENTS_ACTION = 'GET_IMPORT_ADJUSTMENTS_ACTION'
export const GET_IMPORT_ADJUSTMENTS_DETAIL_ACTION = 'GET_IMPORT_ADJUSTMENTS_DETAIL_ACTION'
export const GET_IMPORT_BORROWINGS_ACTION = 'GET_IMPORT_BORROWINGS_ACTION'
export const GET_IMPORT_BORROWINGS_DETAIL_ACTION = 'GET_IMPORT_BORROWINGS_DETAIL_ACTION'
export const PUT_NOT_IMPORT_ACTION = 'PUT_NOT_IMPORT_ACTION'
export const POST_SALE_IMPORT_ACTION = 'POST_SALE_IMPORT_ACTION'
export const GET_RECEIPTS_ACTION = 'GET_RECEIPTS_ACTION'
export const EXPORT_RECEIPTS_ACTION = 'EXPORT_RECEIPTS_ACTION'
