export const SALES = 'sales'

// Getters
export const VOUCHERS_GETTER = 'VOUCHERS_GETTER'
export const ONLINE_ORDERS_GETTER = 'ONLINE_ORDERS_GETTER'
export const ONLINE_ORDERS_PAGINATION_GETTER = 'ONLINE_ORDERS_PAGINATION_GETTER'

// Actions
export const GET_VOUCHERS_ACTION = 'GET_VOUCHERS_ACTION'
export const GET_ONLINE_ORDERS_ACTION = 'GET_ONLINE_ORDERS_ACTION'
