export const SALES = 'sales'

// Getters
export const VOUCHERS_GETTER = 'VOUCHERS_GETTER'
export const ONLINEORDERS_GETTER = 'ONLINEORDERS_GETTER'
export const ONLINEORDERS_PAGINATION_GETTER = 'ONLINEORDERS_PAGINATION_GETTER'

// Actions
export const GET_VOUCHERS_ACTION = 'GET_VOUCHERS_ACTION'
export const GET_ONLINEORDERS_ACTION = 'GET_ONLINEORDERS_ACTION'
