export const REPORT_WAREHOUSES_INPUT = 'reportWarehousesInput'

// Getters
export const REPORT_WAREHOUSES_INPUT_GETTER = 'REPORT_WAREHOUSES_INPUT_GETTER'
// Actions
export const GET_REPORT_WAREHOUSES_INPUT_ACTION = 'GET_REPORT_WAREHOUSES_INPUT_ACTION'
export const EXPORT_REPORT_WAREHOUSES_INPUT_ACTION = 'EXPORT_REPORT_WAREHOUSES_INPUT_ACTION'
