export const REPORT_SALES = 'reportSales'

// Getters
export const REPORT_SALES_GETTER = 'REPORT_SALES_GETTER'
export const PRODUCT_CATS_GETTER = 'PRODUCT_CATS_GETTER'
export const PRODUCTS_GETTER = 'PRODUCTS_GETTER'
export const BILL_COLLECTORS_GETTER = 'BILL_COLLECTORS_GETTER'
// Mutations
export const CLEAR_ALL_PRODUCTS_CHECKED_MUTATION = 'CLEAR_ALL_PRODUCTS_CHECKED_MUTATION'
// Actions
export const GET_REPORT_SALES_ACTION = 'GET_REPORT_SALES_ACTION'
export const EXPORT_REPORT_SALES_ACTION = 'EXPORT_REPORT_SALES_ACTION'
export const GET_PRODUCTS_ACTION = 'GET_PRODUCTS_ACTION'
export const GET_PRODUCT_CATS_ACTION = 'GET_PRODUCT_CATS_ACTION'
export const GET_BILL_COLLECTORS_ACTION = 'GET_BILL_COLLECTORS_ACTION'
