export const PURCHASES = 'purchases'

// Getters
export const GET_PO_LIST_GETTER = 'GET_PO_LIST_GETTER'
export const GET_PO_SEARCH_LIST_GETTER = 'GET_PO_SEARCH_LIST_GETTER'
export const GET_PO_AUTO_PRODUCT_GETTER = 'GET_PO_AUTO_PRODUCT_GETTER'
export const GET_PRODUCT_GETTER = 'GET_PRODUCT_GETTER'
export const GET_PO_REQUEST_LIST_GETTER = 'GET_PO_REQUEST_LIST_GETTER'
export const POST_CANCEL_PO_GETTER = 'POST_CANCEL_PO_GETTER'
export const POST_APPROVE_PO_GETTER = 'POST_APPROVE_PO_GETTER'
export const POST_SAVE_PO_GETTER = 'POST_SAVE_PO_GETTER'

// Actions
export const GET_PO_LIST_ACTION = 'GET_PO_LIST_ACTION'
export const GET_PO_SEARCH_LIST_ACTION = 'GET_PO_SEARCH_LIST_ACTION'
export const GET_PO_AUTO_PRODUCT_ACTION = 'GET_PO_AUTO_PRODUCT_ACTION'
export const GET_PRODUCT_ACTION = 'GET_PRODUCT_ACTION'
export const GET_PO_REQUEST_LIST_ACTION = 'GET_PO_REQUEST_LIST_ACTION'
export const POST_CANCEL_PO_ACTION = 'POST_CANCEL_PO_ACTION'
export const POST_APPROVE_PO_ACTION = 'POST_APPROVE_PO_ACTION'
export const POST_SAVE_PO_ACTION = 'POST_SAVE_PO_ACTION'
