export const RETURNEDGOODS = 'salesReturnedGoods'

// Getters
export const RETURNED_GOODS_GETTER = 'RETURNED_GOODS_GETTER'
export const RETURNED_GOOD_CHOOSE_GETTER = 'RETURNED_GOOD_CHOOSE_GETTER'
export const RETURNED_GOOD_CHOOSEN_DETAIL_GETTER = 'RETURNED_GOOD_CHOOSEN_DETAIL_GETTER'

// Mutations
export const CLEAR_RETURNED_GOODS_DATA = 'CLEAR_RETURNED_GOODS_DATA'

// Actions
export const GET_RETURNED_GOODS_ACTION = 'GET_RETURNED_GOODS_ACTION'
export const GET_RETURNED_GOOD_CHOOSE_ACTION = 'GET_RETURNED_GOOD_CHOOSE_ACTION'
export const GET_RETURNED_GOOD_CHOOSEN_DETAIL_ACTION = 'GET_RETURNED_GOOD_CHOOSEN_DETAIL_ACTION'
export const CREATE_RETURNED_GOOD_ACTION = 'CREATE_RETURNED_GOOD_ACTION'
