export const PRINTERCONFIG = 'printerConfig'

// GETTERs
export const PRINTER_CLIENT_GETTER = 'PRINTER_CLIENT_GETTER'

// ACTIONS
export const GET_PRINTER_CLIENT_ACTIONS = 'GET_PRINTER_CLIENT_ACTIONS'
export const CREATE_PRINTER_CLIENT_ACTIONS = 'CREATE_PRINTER_CLIENT_ACTIONS'
export const UPDATE_PRINTER_CLIENT_ACTIONS = 'UPDATE_PRINTER_CLIENT_ACTIONS'
