export const REPORT_SALES_CAT = 'reportSalesCat'

// Getters
export const REPORT_SALES_CAT_GETTER = 'REPORT_SALES_CAT_GETTER'
export const CUSTOMER_TYPES_GETTER = 'CUSTOMER_TYPES_GETTER'
export const PRINT_REPORT_GETTER = 'PRINT_REPORT_GETTER'

// Actions
export const GET_REPORT_SALES_CAT_ACTION = 'GET_REPORT_SALES_CAT_ACTION'
export const EXPORT_REPORT_SALES_CAT_ACTION = 'EXPORT_REPORT_SALES_CAT_ACTION'
export const GET_CUSTOMER_TYPES_ACTION = 'GET_CUSTOMER_TYPES_ACTION'
export const PRINT_REPORT_ACTION = 'PRINT_REPORT_ACTION'
