export const REPORT_WAREHOUSES_ADJUSTMENTS = 'reportsWarehousesAdjustment'

// Getters
export const REPORT_WAREHOUSES_ADJUSTMENTS_GETTER = 'REPORT_WAREHOUSES_ADJUSTMENTS_GETTER'
export const PRODUCT_CAT_LISTS_GETTER = 'PRODUCT_CAT_LISTS_GETTER'
export const PRODUCT_LISTS_GETTER = 'PRODUCT_LISTS_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_ADJUSTMENTS_ACTION = 'GET_REPORT_WAREHOUSES_ADJUSTMENTS_ACTION'
export const GET_PRODUCT_LISTS_ACTION = 'GET_PRODUCT_LISTS_ACTION'
export const GET_PRODUCT_CAT_LISTS_ACTION = 'GET_PRODUCT_CAT_LISTS_ACTION'
export const EXPORT_REPORT_WAREHOUSES_ADJUSTMENTS_ACTION = 'EXPORT_REPORT_WAREHOUSES_ADJUSTMENTS_ACTION'
