export const REPORT_WAREHOUSES_ADJUSTMENTS = 'reportsWarehousesAdjustment'

// Getters
export const REPORT_WAREHOUSES_ADJUSTMENTS_GETTER = 'REPORT_WAREHOUSES_ADJUSTMENTS_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_ADJUSTMENTS_ACTIONS = 'GET_REPORT_WAREHOUSES_ADJUSTMENTS_ACTIONS'
