export const REPORT_OUTPUT_GOODS = 'reportsWarehousesOutput'

// Getters
export const OUTPUT_GOODS_GETTER = 'OUTPUT_GOODS_GETTER'
export const PRODUCT_CAT_GETTER = 'PRODUCT_CAT_GETTER'
export const PRODUCT_GETTER = 'PRODUCT_GETTER'
export const PRINT_OUTPUT_GOODS_GETTER = 'PRINT_OUTPUT_GOODS_GETTER'

// Actions
export const GET_OUTPUT_GOODS_ACTION = 'GET_OUTPUT_GOODS_ACTION'
export const GET_PRODUCT_ACTION = 'GET_PRODUCT_ACTION'
export const GET_PRODUCT_CAT_ACTION = 'GET_PRODUCT_CAT_ACTION'
export const EXPORT_OUTPUT_GOODS_ACTION = 'EXPORT_OUTPUT_GOODS_ACTION'
export const PRINT_OUTPUT_GOODS_ACTION = 'PRINT_OUTPUT_GOODS_ACTION'
