export const SALESRECEIPTS = 'salesReceipts'

// GETTER
export const SALES_RECEIPTS_GETTER = 'SALES_RECEIPTS_GETTER'
export const SALES_RECEIPTS_INFO_GETTER = 'SALES_RECEIPTS_INFO_GETTER'

// ACTION
export const GET_SALES_RECEIPTS_ACTION = 'GET_SALES_RECEIPTS_ACTION'
