export const SALESRECEIPTS = 'salesReceipts'

// GETTER
export const SALES_RECEIPTS_GETTER = 'SALES_RECEIPTS_GETTER'
export const SALES_RECEIPTS_DETAIL_GETTER = 'SALES_RECEIPTS_DETAIL_GETTER'
export const SALES_RECEIPTS_DETAIL_TOTAL_GETTER = 'SALES_RECEIPTS_DETAIL_TOTAL_GETTER'
export const SALES_RECEIPTS_DISCOUNT_GETTER = 'SALES_RECEIPTS_DISCOUNT_GETTER'
export const SALES_RECEIPTS_PROMOTION_GETTER = 'SALES_RECEIPTS_PROMOTION_GETTER'
export const SALES_RECEIPT_DETAIL_INFOS_GETTER = 'SALES_RECEIPT_DETAIL_INFOS_GETTER'
export const SALES_RECEIPTS_DETAIL_TOTAL_INFOS_GETTER = 'SALES_RECEIPTS_DETAIL_TOTAL_INFOS_GETTER'
export const SALES_RECEIPTS_PAGINATION_GETTER = 'SALES_RECEIPTS_PAGINATION_GETTER'
export const PRINT_SALES_RECEIPT_GETTER = 'PRINT_SALES_RECEIPT_GETTER'
// ACTION
export const GET_SALES_RECEIPTS_ACTION = 'GET_SALES_RECEIPTS_ACTION'
export const GET_SALES_RECEIPTS_DETAIL_ACTION = 'GET_SALES_RECEIPTS_DETAIL_ACTION'
export const PRINT_SALES_RECEIPT_ACTION = 'PRINT_SALES_RECEIPT_ACTION'
