export const REPORT_SALES_SALE_RECEIPT = 'reportSalesSaleReceiptPerCustomer'

// Getters
export const REPORT_SALES_SALE_RECEIPT_GETTER = 'REPORT_SALES_SALE_RECEIPT_GETTER'
export const REPORT_SALES_SALE_RECEIPT_CONTENT_GETTER = 'REPORT_SALES_SALE_RECEIPT_CONTENT_GETTER'
export const REPORT_SALES_CUSTOMER_TYPES_GETTER = 'REPORT_SALES_CUSTOMER_TYPE_GETTER'
// Actions
export const GET_CUSTOMERS_TYPES_ACTION = 'GET_CUSTOMERS_TYPES_ACTION'
export const GET_SALE_RECEIPTS_ACTION = 'GET_SALE_RECEIPTS_ACTION'
export const EXPORT_REPORT_SALE_RECEIPT_AMOUNT_ACTION = 'EXPORT_REPORT_SALE_RECEIPT_AMOUNT_ACTION'
