export const REPORT_VOUCHERS = 'reportVouchers'

// Getters
export const REPORT_VOUCHERS_USED_GETTER = 'REPORT_VOUCHERS_USED_GETTER'
// Actions
export const GET_REPORT_VOUCHERS_USED_ACTION = 'GET_REPORT_VOUCHERS_USED_ACTION'
export const EXPORT_REPORT_VOUCHERS_USED_ACTION = 'EXPORT_REPORT_VOUCHERS_USED_ACTION'
