export const REPORT_WAREHOUSES_PROMOTIONS = 'reportswarehousesPromotion'

// Getters
export const REPORT_WAREHOUSES_PROMOTIONS_GETTER = 'REPORT_WAREHOUSES_PROMOTIONS_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_PROMOTIONS_ACTIONS = 'GET_REPORT_WAREHOUSES_PROMOTIONS_ACTIONS'
