export const REPORT_WAREHOUSES_PROMOTIONS = 'reportsWarehousesPromotion'

// Getters
export const REPORT_WAREHOUSES_PROMOTIONS_GETTER = 'REPORT_WAREHOUSES_PROMOTIONS_GETTER'
export const PRODUCT_CAT_GETTER = 'PRODUCT_CAT_GETTER'
export const PRODUCT_GETTER = 'PRODUCT_GETTER'
export const PRINT_REPORT_PROMOTION_GETTER = 'PRINT_REPORT_PROMOTION_GETTER'

// Actions
export const GET_REPORT_WAREHOUSES_PROMOTIONS_ACTIONS = 'GET_REPORT_WAREHOUSES_PROMOTIONS_ACTIONS'
export const GET_PRODUCT_ACTION = 'GET_PRODUCT_ACTION'
export const GET_PRODUCT_CAT_ACTION = 'GET_PRODUCT_CAT_ACTION'
export const EXPORT_REPORT_WAREHOUSES_PROMOTIONS_ACTION = 'EXPORT_REPORT_WAREHOUSES_PROMOTIONS_ACTION'
export const PRINT_REPORT_PROMOTION_ACTION = 'PRINT_REPORT_PROMOTION_ACTION'
