export const REPORT_WAREHOUSES_INVENTORY = 'reportWarehousesInventory'

// GETTERS
export const REPORT_WAREHOUSES_INVENTORY_GETTER = 'REPORT_WAREHOUSES_INVENTORY_GETTER'
export const REPORT_WAREHOUSES_INVENTORY_INFO_GETTER = 'REPORT_WAREHOUSES_INVENTORY_INFO_GETTER'

// ACTIONS
export const GET_REPORT_WAREHOUSES_INVENTORY_ACTION = 'GET_REPORT_WAREHOUSES_INVENTORY_ACTION'
