export const REPORT_WAREHOUSES_INVENTORY = 'reportWarehousesInventory'

// GETTERS
export const REPORT_WAREHOUSES_INVENTORY_GETTER = 'REPORT_WAREHOUSES_INVENTORY_GETTER'
export const REPORT_WAREHOUSES_INVENTORY_INFO_GETTER = 'REPORT_WAREHOUSES_INVENTORY_INFO_GETTER'
export const REPORT_WAREHOUSES_INVENTORY_PAGINATION_GETTER = 'REPORT_WAREHOUSES_INVENTORY_PAGINATION_GETTER'
export const PRODUCT_LIST_GETTER = 'PRODUCT_LIST_GETTER'
export const PRODUCT_LIST_PAGINATION_GETTER = 'PRODUCT_LIST_PAGINATION_GETTER'
export const PRODUCT_CAT_LIST_GETTER = 'PRODUCT_CAT_LIST_GETTER'
export const PRINT_REPORT_INVENTORY_GETTER = 'PRINT_REPORT_INVENTORY_GETTER'
// ACTIONS
export const GET_REPORT_WAREHOUSES_INVENTORY_ACTION = 'GET_REPORT_WAREHOUSES_INVENTORY_ACTION'
export const EXPORT_REPORT_INVENTORIES_ACTION = 'EXPORT_REPORT_INVENTORIES_ACTION'
export const GET_PRODUCT_LIST_ACTION = 'GET_PRODUCT_LIST_ACTION'
export const GET_PRODUCT_CAT_LIST_ACTION = 'GET_PRODUCT_CAT_LIST_ACTION'
export const PRINT_REPORT_INVENTORY_ACTION = 'PRINT_REPORT_INVENTORY_ACTION'
