const SALES = '/sales'
const RED_INVOICES = '/red-invoices'
export const getRedInvoiceEndpoint = `${SALES}${RED_INVOICES}`
export const getCustomersEndpoint = '/customers'
export const getBillOfSalesEndPoint = `${SALES}${RED_INVOICES}/bill-of-sale-list`
export const getBillOfSaleProductsEndPoint = `${SALES}${RED_INVOICES}/show-info-product`
export const getProductsEndPoint = `${SALES}${RED_INVOICES}/search-product`
export const createRedBillEndpoint = `${SALES}${RED_INVOICES}/create`
export const getInvoiceDetailEndpoint = `${SALES}${RED_INVOICES}/show-invoice-details`
