export const WAREHOUSES_COMBO = 'warehousesCombo'

// Getters
export const GET_WAREHOUSE_COMBO_DETAIL_GETTER = 'GET_WAREHOUSE_COMBO_DETAIL_GETTER'
export const WAREHOUSES_COMBO_GETTER = 'WAREHOUSES_COMBO_GETTER'
export const WAREHOUSES_COMBO_PAGINATION_GETTER = 'WAREHOUSES_COMBO_PAGINATION_GETTER'
export const WAREHOUSES_COMBO_TOTAL_INFO_GETTER = 'WAREHOUSES_COMBO_TOTAL_INFO_GETTER'

// Actions
export const GET_WAREHOUSE_COMBO_DETAIL_ACTION = 'GET_WAREHOUSE_COMBO_DETAIL_ACTION'
export const GET_WAREHOUSES_COMBO_ACTIONS = 'GET_WAREHOUSES_COMBO_ACTIONS'
