export const WAREHOUSECOMBO = 'warehousesCombo'

// Getters
export const GET_WARE_HOUSE_COMBO_DETAIL_GETTER = 'GET_WARE_HOUSE_COMBO_DETAIL_GETTER'

// Actions
export const GET_WARE_HOUSE_COMBO_DETAIL_ACTION = 'GET_WARE_HOUSE_COMBO_DETAIL_ACTION'
