export const WAREHOUSES_COMBO = 'warehousesCombo'

// Getters
export const GET_WAREHOUSE_COMBO_DETAIL_GETTER = 'GET_WAREHOUSE_COMBO_DETAIL_GETTER'
export const WAREHOUSES_COMBO_GETTER = 'WAREHOUSES_COMBO_GETTER'
export const WAREHOUSES_COMBO_PAGINATION_GETTER = 'WAREHOUSES_COMBO_PAGINATION_GETTER'
export const WAREHOUSES_COMBO_TOTAL_INFO_GETTER = 'WAREHOUSES_COMBO_TOTAL_INFO_GETTER'
export const COMBO_PRODUCTS_GETTER = 'COMBO_PRODUCTS_GETTER'
export const COMBO_PRODUCTS_DETAILS_GETTER = 'COMBO_PRODUCTS_DETAILS_GETTER'
export const COMBO_PRODUCTS_INFO_GETTER = 'COMBO_PRODUCTS_INFO_GETTER'

// Actions
export const GET_WAREHOUSE_COMBO_DETAIL_ACTION = 'GET_WAREHOUSE_COMBO_DETAIL_ACTION'
export const GET_WAREHOUSES_COMBO_ACTIONS = 'GET_WAREHOUSES_COMBO_ACTIONS'
export const GET_COMBO_PRODUCTS_ACTION = 'GET_COMBO_PRODUCTS_ACTION'
export const GET_COMBO_PRODUCTS_DETAILS_ACTION = 'GET_COMBO_PRODUCTS_DETAILS_ACTION'
export const CREATE_COMBO_PRODUCT_ACTION = 'CREATE_COMBO_PRODUCT_ACTION'
