export const WAREHOUSEINVENTORY = 'warehousesInventory'

export const WAREHOUSE_INVENTORIES_GETTER = 'WAREHOUSE_INVENTORIES_GETTER'
export const WAREHOUSE_INVENTORY_PAGINATION_GETTER = 'WAREHOUSE_INVENTORY_PAGINATION_GETTER'
export const WAREHOUSE_TYPES_GETTER = 'WAREHOUSE_TYPES_GETTER'

export const GET_WAREHOUSE_INVENTORIES_ACTION = 'GET_WAREHOUSE_INVENTORIES_ACTION'
export const GET_WAREHOUSE_TYPES_ACTION = 'GET_WAREHOUSE_TYPES_ACTION'
