export const REPORT_RETURNED_GOODS = 'reportsReturnedGoods'

// Getters
export const REPORT_RETURNED_GOODS_GETTER = 'REPORT_RETURNED_GOODS_GETTER'
export const PRODUCT_CAT_LISTS_GETTER = 'PRODUCT_CAT_LISTS_GETTER'
export const PRODUCT_LISTS_GETTER = 'PRODUCT_LISTS_GETTER'
export const PRINT_INPUT_ORDER_DETIAL_GETTER = 'PRINT_INPUT_ORDER_DETIAL_GETTER' // temp
export const PRINT_SELLS_GETTER = 'PRINT_SELLS_GETTER' // temp
export const PRINT_RETURN_GOODS_GETTER = 'PRINT_RETURN_GOODS_GETTER'

// mutations
export const CLEAR_ALL_PRODUCT_LISTS_CHECKED = 'CLEAR_ALL_PRODUCT_LISTS_CHECKED'

// Actions
export const GET_REPORT_RETURNED_GOODS_ACTION = 'GET_REPORT_RETURNED_GOODS_ACTION'
export const EXPORT_REPORT_RETURNED_GOODS_ACTION = 'EXPORT_REPORT_RETURNED_GOODS_ACTION'
export const GET_PRODUCT_LISTS_ACTIONS = 'GET_PRODUCT_LISTS_ACTIONS'
export const GET_PRODUCT_CAT_LISTS_ACTIONS = 'GET_PRODUCT_CAT_LISTS_ACTIONS'
export const PRINT_INPUT_ORDER_DETIAL_ACTION = 'PRINT_INPUT_ORDER_DETIAL_ACTION' // temp
export const PRINT_SELLS_ACTION = 'PRINT_SELLS_ACTION' // temp
export const PRINT_RETURN_GOODS_ACTION = 'PRINT_RETURN_GOODS_ACTION'
