export const REPORT_RETURNED_GOODS = 'reportsReturnedGoods'

// Getters
export const REPORT_RETURNED_GOODS_GETTER = 'REPORT_RETURNED_GOODS_GETTER'
export const PRODUCT_CAT_LISTS_GETTER = 'PRODUCT_CAT_LISTS_GETTER'
export const PRODUCT_LISTS_GETTER = 'PRODUCT_LISTS_GETTER'

// Actions
export const GET_REPORT_RETURNED_GOODS_ACTION = 'GET_REPORT_RETURNED_GOODS_ACTION'
export const EXPORT_REPORT_RETURNED_GOODS_ACTION = 'EXPORT_REPORT_RETURNED_GOODS_ACTION'
export const GET_PRODUCT_LISTS_ACTIONS = 'GET_PRODUCT_LISTS_ACTIONS'
export const GET_PRODUCT_CAT_LISTS_ACTIONS = 'GET_PRODUCT_CAT_LISTS_ACTIONS'
