export const REPORT_RETURNED_GOODS = 'reportsReturnedGoods'

// Getters
export const REPORT_RETURNED_GOODS_GETTER = 'REPORT_RETURNED_GOODS_GETTER'
export const REPORT_RETURNED_GOODS_PAGINATION_GETTER = 'REPORT_RETURNED_GOODS_PAGINATION_GETTER'
export const REPORT_RETURNED_GOODS_TOTAL_INFO_GETTER = 'REPORT_RETURNED_GOODS_TOTAL_INFO_GETTER'

// Actions
export const GET_REPORT_RETURNED_GOODS_ACTION = 'GET_REPORT_RETURNED_GOODS_ACTION'
export const EXPORT_REPORT_RETURNED_GOODS_ACTION = 'EXPORT_REPORT_RETURNED_GOODS_ACTION'
